/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import Logic.History;
import Logic.Product.product;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 ** @author Karla

 *
 */
public class HistoryProductView extends javax.swing.JFrame {

    private String productAmount = "";
    private String productName = "";
    private String unitPrice = "";
    private String totalPrice = "";
    private Iterable<History> histories;
  

    /**
     * Creates new form HistoryProductView
     */
    public HistoryProductView() {
        initComponents();
        try {
 
            setPurchaseOrders();
            
            int id = getPurchaseID();
            if (id != -1)
                getTable(id);
        } catch (Exception e) {
        }
        
    }
    //
    private void setPurchaseOrders() {
     
        for (History history : histories) {
            if (history.getUserID().equals(product.getID())) {
                purchaseOrdersBox.addItem(String.valueOf(history.getPurchaseID()));
            }
        }
    }
    //
    private int getPurchaseID() {
      
        if (purchaseOrdersBox.getItemCount() > 0)
            return Integer.parseInt(purchaseOrdersBox.getSelectedItem().toString());
        else
            return -1;
    }
    //
    private void setTable() {
        showHistoryProductTable.addMouseListener(new MouseAdapter() {
            DefaultTableModel model = new DefaultTableModel();

            @Override
            public void mouseClicked(MouseEvent e) {
                int i = showHistoryProductTable.getSelectedRow();
                productName = (showHistoryProductTable.getValueAt(i, 0).toString());
                productAmount = (showHistoryProductTable.getValueAt(i, 1).toString());
                unitPrice = (showHistoryProductTable.getValueAt(i, 2).toString());
                totalPrice = (showHistoryProductTable.getValueAt(i, 3).toString());
            }
        });
    }
    //
    private void getTable(int purchaseID) {
        PurchaseOrder item;
        History history = histories.get(purchaseID);
        int listSize = history.getItems().size();
        if (listSize != 0) {
            String tableArray[][] = new String[listSize][4];
            for (int i = 0; i < listSize; i++) {
                item = history.getItems().get(i);
                tableArray[i][0] = item.getName();
                tableArray[i][1] = String.valueOf(item.getQuantity());
                tableArray[i][2] = "$" + String.valueOf(item.getUnitPrice() + " c/u");
                tableArray[i][3] = "$" + String.valueOf(item.getTotalPrice());
            }
            showHistoryProductTable.setModel(new javax.swing.table.DefaultTableModel(
                    tableArray,
                    new String[]{
                        "Name", "Amount", "Unit Price", "Total Price"
                    }
            ));
        }
    }
    //
    private void QualifyProduct(int purchaseID) {
        
    }
    //
    private void QualifyWindow() {
        QualifyView qualify = new QualifyView();
        qualify.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        showHistoryProductTable = new javax.swing.JTable();
        purchaseOrdersBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        QualifyButton = new javax.swing.JButton();
        back = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        showHistoryProductTable.setForeground(new java.awt.Color(0, 153, 153));
        showHistoryProductTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Product Amount", "Unit Price", "Total Price"
            }
        ));
        showHistoryProductTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        showHistoryProductTable.setDropMode(javax.swing.DropMode.INSERT);
        jScrollPane1.setViewportView(showHistoryProductTable);

        purchaseOrdersBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                purchaseOrdersBoxItemStateChanged(evt);
            }
        });
        purchaseOrdersBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseOrdersBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Purchase Orders");

        QualifyButton.setText("view");
        QualifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QualifyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(purchaseOrdersBox, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(QualifyButton)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(purchaseOrdersBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(QualifyButton)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        back.setBorder(null);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/return.png"))); // NOI18N
        jMenu1.setFocusable(false);
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        back.add(jMenu1);

        setJMenuBar(back);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
    
    }//GEN-LAST:event_jMenu1MouseClicked

    private void purchaseOrdersBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseOrdersBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_purchaseOrdersBoxActionPerformed

    private void purchaseOrdersBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_purchaseOrdersBoxItemStateChanged
        getTable(getPurchaseID());
    }//GEN-LAST:event_purchaseOrdersBoxItemStateChanged

    private void QualifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QualifyButtonActionPerformed
        QualifyProduct(getPurchaseID());
    }//GEN-LAST:event_QualifyButtonActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistoryProductView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistoryProductView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistoryProductView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistoryProductView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistoryProductView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton QualifyButton;
    private javax.swing.JMenuBar back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> purchaseOrdersBox;
    private javax.swing.JTable showHistoryProductTable;
    // End of variables declaration//GEN-END:variables

    private static class PurchaseOrder {

        public PurchaseOrder() {
        }

        private Object getQuantity() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        private String getUnitPrice() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        private Object getTotalPrice() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        private String getName() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }

    private static class histories {

        private static History get(int purchaseID) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public histories() {
        }
    }

    private static class QualifyView {

        public QualifyView() {
        }

        private void setVisible(boolean b) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }
}
